[build]
  # Directory to change to before starting a build
  base = "/"
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  # Default build command
  command = "npm run netlify-build"
  # Node.js version to use for build
  NODE_VERSION = "20"
  # NPM version to use for build
  NPM_VERSION = "10"

[functions]
  # Directory where Netlify will look for your functions
  directory = "netlify/functions"

[dev]
  # For local development
  functions = "netlify/functions"
  targetPort = 5173  # Vite's default port

# Redirects for SPA (Single Page Application) - handles client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.googletagmanager.com https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com;"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"